import { Lexend , Lexend_Tera } from "next/font/google";
import React from 'react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this file is where the site's header and footer should go

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
